### PR TITLE
Destroy the socket when done.

### PR DESCRIPTION
**Pull request by ghost**
In a long-running SMTP server, dnsbl currently leaves a listening UDP socket open each time it's called.

The solution is to destroy the socket before returning.

### CODE REVIEW

**Comment by silverwind** [comment]
Good idea, but I think the right place to destroy is on [this line](https://github.com/silverwind/dnsbl/blob/773fc485f7f80647e96b840220cfa9a634e296b6/index.js#L34). `.batch` reuses the socket multiple times and destroys it at the end, and the same should be done after `.lookup` is done. So I think you can change the line like this:

````patch
diff --git a/index.js b/index.js
index ff3367e..c9cf1e7 100644
--- a/index.js
+++ b/index.js
@@ -31,7 +31,10 @@ module.exports.lookup = function lookup(addr, blacklist, opts) {
   opts = Object.assign({}, defaults, opts);
   const socket = dns({timeout: opts.timeout});

-  return queryFactory(addr, blacklist, socket, opts)();
+  return queryFactory(addr, blacklist, socket, opts)().then(function(result) {
+    socket.destroy();
+    return result;
+  });
 };
````

**Comment by CliffS** [comment]
Fair enough, I had forgotten about batch mode.

I'll close this PR and let you fix it the right way.  Thanks for the quick response.

**Comment by silverwind** [comment]
Fix is released as v1.1.5.

**Comment by CliffS** [comment]
On 11/03/17 19:39, silverwind wrote:

> Fix is released as v1.1.5.

You're a star.  Thanks.

Regards
Cliff.


-- 
Cliff Stanford
London:  +44 20 0222 1666
Swansea: +44 1792 469 666
Spain:   +34  603 777 666
Mobile:  +44 7973 616 666

**Pull request closed without merging**
